#!/usr/bin/env python3
# This file was generated by claude.ai in December 2025 and used only to
# create the geometry of capsule.stl since the original SIM_splashdown
# from Trick this example was inspired by did not provide a file capable
# of being read by VTK.
import numpy as np

def generate_capsule_stl(filename='capsule.stl', radius=1.0, height=1.5, resolution=32):
    """
    Generate a spacecraft re-entry capsule shaped STL file.
    
    Parameters:
    - radius: base radius of the capsule
    - height: total height of the capsule
    - resolution: number of segments around the circumference
    """
    
    vertices = []
    faces = []
    
    # Create the rounded heat shield bottom (hemisphere-like)
    shield_height = radius * 0.6  # Slightly flattened hemisphere
    
    # Bottom center point
    bottom_center = [0, 0, -shield_height]
    vertices.append(bottom_center)
    bottom_center_idx = 0
    
    # Create heat shield surface points
    shield_layers = 8
    for i in range(1, shield_layers + 1):
        theta = (i / shield_layers) * (np.pi / 2)  # 0 to 90 degrees
        layer_radius = radius * np.sin(theta)
        layer_z = -shield_height * np.cos(theta)
        
        for j in range(resolution):
            angle = 2 * np.pi * j / resolution
            x = layer_radius * np.cos(angle)
            y = layer_radius * np.sin(angle)
            vertices.append([x, y, layer_z])
    
    # Create triangular faces for heat shield
    for i in range(shield_layers):
        if i == 0:
            # Connect bottom center to first ring
            for j in range(resolution):
                j_next = (j + 1) % resolution
                faces.append([bottom_center_idx, 1 + j_next, 1 + j])
        else:
            # Connect rings
            base_idx = 1 + (i - 1) * resolution
            next_idx = 1 + i * resolution
            for j in range(resolution):
                j_next = (j + 1) % resolution
                # Two triangles per quad
                faces.append([base_idx + j, next_idx + j, base_idx + j_next])
                faces.append([base_idx + j_next, next_idx + j, next_idx + j_next])
    
    # Top cone section
    cone_base_idx = len(vertices)
    cone_height = height - shield_height
    
    # Add cone base vertices (same as last shield layer)
    for j in range(resolution):
        angle = 2 * np.pi * j / resolution
        x = radius * np.cos(angle)
        y = radius * np.sin(angle)
        vertices.append([x, y, 0])
    
    # Add cone middle sections
    cone_layers = 6
    for i in range(1, cone_layers):
        t = i / cone_layers
        layer_radius = radius * (1 - t * 0.7)  # Taper to 30% of base radius
        layer_z = cone_height * t
        
        for j in range(resolution):
            angle = 2 * np.pi * j / resolution
            x = layer_radius * np.cos(angle)
            y = layer_radius * np.sin(angle)
            vertices.append([x, y, layer_z])
    
    # Top center point
    top_radius = radius * 0.3
    vertices.append([0, 0, cone_height])
    top_center_idx = len(vertices) - 1
    
    # Connect heat shield to cone base
    last_shield_base = 1 + (shield_layers - 1) * resolution
    for j in range(resolution):
        j_next = (j + 1) % resolution
        faces.append([last_shield_base + j, cone_base_idx + j, last_shield_base + j_next])
        faces.append([last_shield_base + j_next, cone_base_idx + j, cone_base_idx + j_next])
    
    # Create cone faces
    for i in range(cone_layers - 1):
        base_idx = cone_base_idx + i * resolution
        next_idx = cone_base_idx + (i + 1) * resolution
        
        for j in range(resolution):
            j_next = (j + 1) % resolution
            faces.append([base_idx + j, next_idx + j, base_idx + j_next])
            faces.append([base_idx + j_next, next_idx + j, next_idx + j_next])
    
    # Connect top ring to apex
    last_cone_ring = cone_base_idx + (cone_layers - 1) * resolution
    for j in range(resolution):
        j_next = (j + 1) % resolution
        faces.append([last_cone_ring + j, top_center_idx, last_cone_ring + j_next])
    
    # Write STL file
    with open(filename, 'w') as f:
        f.write('solid capsule\n')
        
        for face in faces:
            v1 = np.array(vertices[face[0]])
            v2 = np.array(vertices[face[1]])
            v3 = np.array(vertices[face[2]])
            
            # Calculate normal
            edge1 = v2 - v1
            edge2 = v3 - v1
            normal = np.cross(edge1, edge2)
            norm = np.linalg.norm(normal)
            if norm > 0:
                normal = normal / norm
            
            f.write(f'  facet normal {normal[0]:.6e} {normal[1]:.6e} {normal[2]:.6e}\n')
            f.write('    outer loop\n')
            f.write(f'      vertex {v1[0]:.6e} {v1[1]:.6e} {v1[2]:.6e}\n')
            f.write(f'      vertex {v2[0]:.6e} {v2[1]:.6e} {v2[2]:.6e}\n')
            f.write(f'      vertex {v3[0]:.6e} {v3[1]:.6e} {v3[2]:.6e}\n')
            f.write('    endloop\n')
            f.write('  endfacet\n')
        
        f.write('endsolid capsule\n')
    
    print(f"Generated {filename} with {len(vertices)} vertices and {len(faces)} faces")

# Generate the capsule
generate_capsule_stl('capsule.stl', radius=1.0, height=1.5, resolution=32)

print("\nTo use with VTK:")
print("import vtk")
print("reader = vtk.vtkSTLReader()")
print("reader.SetFileName('capsule.stl')")
print("reader.Update()")
